#!/bin/sh
# postinst script for calamares-settings-ubuntudde
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package

if [ "$1" = "configure" ]; then
    if [ -f /home/ubuntudde/Desktop/ubuntudde-calamares.desktop ]; then
        chown -R 999:999 /home/ubuntudde/Desktop/
    fi
fi

#DEBHELPER#

exit 0

